// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc0.PracticeRobot2015;
    
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveTrainLeftTalon1;
    public static SpeedController driveTrainLeftTalon2;
    public static SpeedController driveTrainRightTalon1;
    public static SpeedController driveTrainRightTalon2;
    public static RobotDrive driveTrainRobotDrive41;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainLeftTalon1 = new TalonSRX(0);
        LiveWindow.addActuator("DriveTrain", "LeftTalon1", (TalonSRX) driveTrainLeftTalon1);
        
        driveTrainLeftTalon2 = new TalonSRX(1);
        LiveWindow.addActuator("DriveTrain", "LeftTalon2", (TalonSRX) driveTrainLeftTalon2);
        
        driveTrainRightTalon1 = new TalonSRX(2);
        LiveWindow.addActuator("DriveTrain", "RightTalon1", (TalonSRX) driveTrainRightTalon1);
        
        driveTrainRightTalon2 = new TalonSRX(3);
        LiveWindow.addActuator("DriveTrain", "RightTalon2", (TalonSRX) driveTrainRightTalon2);
        
        driveTrainRobotDrive41 = new RobotDrive(driveTrainLeftTalon1, driveTrainLeftTalon2,
              driveTrainRightTalon1, driveTrainRightTalon2);
        
        driveTrainRobotDrive41.setSafetyEnabled(true);
        driveTrainRobotDrive41.setExpiration(0.1);
        driveTrainRobotDrive41.setSensitivity(0.5);
        driveTrainRobotDrive41.setMaxOutput(1.0);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
